import { useEffect, useRef } from 'react';
import { isElitePlan, isProPlan } from '@/lib/plans';

interface UseCopyProtectionOptions {
  plan: string;
  text: string;
}

/**
 * Returns a ref to attach to the output container.
 * Free users: limits copy actions and watermarks clipboard output.
 * Pro/Elite: unrestricted.
 */
export const useCopyProtection = ({ plan, text }: UseCopyProtectionOptions) => {
  const copyCountRef = useRef(0);
  const MAX_FREE_COPIES = 3;

  const isPaid = isProPlan(plan) || isElitePlan(plan);

  const getProtectedText = (): string => {
    if (isPaid) return text;
    return `${text}\n\n---\nGenerated by Sovereign AI (Free) · sovereignapp.pro\nUpgrade to Pro for unlimited access.`;
  };

  const canCopy = (): boolean => {
    if (isPaid) return true;
    return copyCountRef.current < MAX_FREE_COPIES;
  };

  const recordCopy = () => {
    if (!isPaid) {
      copyCountRef.current += 1;
    }
  };

  const copiesRemaining = isPaid ? Infinity : Math.max(0, MAX_FREE_COPIES - copyCountRef.current);

  // Blur text beyond character limit for free users
  const BLUR_AFTER_CHARS = isPaid ? Infinity : 600;

  return {
    getProtectedText,
    canCopy,
    recordCopy,
    copiesRemaining,
    blurAfterChars: BLUR_AFTER_CHARS,
    isPaid,
  };
};

/**
 * ProposalDisplay — renders proposal with blur gate for free users
 */
interface ProposalDisplayProps {
  text: string;
  plan: string;
  onUpgrade: () => void;
}

export const ProposalDisplay = ({ text, plan, onUpgrade }: ProposalDisplayProps) => {
  const isPaid = isProPlan(plan) || isElitePlan(plan);
  const BLUR_AFTER = 600;

  if (isPaid || text.length <= BLUR_AFTER) {
    return (
      <div className="whitespace-pre-wrap text-sm text-foreground leading-relaxed font-mono">
        {text}
      </div>
    );
  }

  const visiblePart = text.slice(0, BLUR_AFTER);
  const blurredPart = text.slice(BLUR_AFTER);

  return (
    <div className="relative">
      <div className="whitespace-pre-wrap text-sm text-foreground leading-relaxed font-mono">
        {visiblePart}
      </div>
      <div className="relative">
        <div
          className="whitespace-pre-wrap text-sm text-foreground leading-relaxed font-mono blur-sm select-none pointer-events-none"
          aria-hidden="true"
        >
          {blurredPart}
        </div>
        {/* Gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-card/70 to-card pointer-events-none" />
        {/* Upgrade gate */}
        <div className="absolute bottom-0 left-0 right-0 flex flex-col items-center py-6">
          <div className="bg-card border border-border rounded-xl px-6 py-4 text-center shadow-xl max-w-xs">
            <p className="text-sm font-medium text-foreground mb-1">Full proposal locked</p>
            <p className="text-xs text-muted-foreground mb-3">Upgrade to Pro to see the complete, unrestricted output</p>
            <button
              onClick={onUpgrade}
              className="w-full px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 transition-opacity"
            >
              Unlock Full Proposal
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
