// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL: string =
  import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY: string =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  '';

// Guard: warn loudly in development if env vars are missing so buttons
// don't silently fail. A placeholder URL prevents createClient() from
// throwing synchronously and crashing the whole module graph.
if (!SUPABASE_URL) {
  console.error(
    '[Sovereign] VITE_SUPABASE_URL is not set. ' +
    'All Supabase/Edge-Function calls will fail. ' +
    'Add it to your .env file and restart the dev server.',
  );
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[Sovereign] VITE_SUPABASE_ANON_KEY is not set. ' +
    'Auth and anonymous requests will fail.',
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

/** Anon key exposed for use in raw fetch() calls to Edge Functions. */
export const supabaseAnonKey = SUPABASE_PUBLISHABLE_KEY;