// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL: string =
  import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY: string =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  '';

// ── Environment validation ────────────────────────────────────────────────────
// `isMisconfigured` is consumed by <EnvConfigBanner> in App.tsx to render a
// high-visibility UI alert when variables are absent (not just a console warning).
export const isMisconfigured = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
export const missingVars: string[] = [
  ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
  ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_ANON_KEY'] : []),
];

if (!SUPABASE_URL) {
  console.error(
    '%c[SOVEREIGN_ERR] VITE_SUPABASE_URL is not set.\n' +
    'All Supabase / Edge-Function calls will fail.\n' +
    'Add it to your Vercel Environment Variables and redeploy.',
    'color:#ef4444;font-weight:bold;font-size:14px',
  );
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '%c[SOVEREIGN_ERR] VITE_SUPABASE_ANON_KEY is not set.\n' +
    'Auth and anonymous requests will fail.\n' +
    'Add it to your Vercel Environment Variables and redeploy.',
    'color:#ef4444;font-weight:bold;font-size:14px',
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

/** Anon key exposed for use in raw fetch() calls to Edge Functions. */
export const supabaseAnonKey = SUPABASE_PUBLISHABLE_KEY;