import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useProfile } from '@/hooks/useProfile';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { getPresetAvatarData } from '@/components/profile/AvatarUpload';
import { MobileBottomNav, SwipeablePageWrapper } from '@/components/MobileBottomNav';
import { useLanguage } from '@/i18n/LanguageContext';
import { User } from '@supabase/supabase-js';
import { getDownloadLimit } from '@/lib/plans';
import { getDownloadsUsedToday, incrementDownloadsUsed } from '@/lib/downloads';
import {
  Crown,
  ArrowLeft,
  Search,
  FileText,
  Trash2,
  Copy,
  Check,
  Loader2,
  Calendar,
  ChevronDown,
  ChevronUp,
  User as UserIcon,
  Settings,
  TrendingUp,
  Clock,
  Download,
  Mail,
} from 'lucide-react';
import { toast } from 'sonner';

interface Proposal {
  id: string;
  job_description: string;
  generated_proposal: string;
  status: string;
  created_at: string;
}

const ProposalsHistory = () => {
  const { t } = useLanguage();
  const navigate = useNavigate();
  const [user, setUser] = useState<User | null>(null);
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [downloadsUsed, setDownloadsUsed] = useState(() => getDownloadsUsedToday());

  const { profile } = useProfile(user);

  const getInitials = (name: string | null) => {
    if (!name) return '';
    return name
      .split(' ')
      .map((n) => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  };

  useEffect(() => {
    const checkAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate('/auth');
        return;
      }
      setUser(session.user);
      fetchProposals(session.user.id);
    };

    checkAuth();

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (!session) {
        navigate('/auth');
      }
    });

    return () => subscription.unsubscribe();
  }, [navigate]);

  const fetchProposals = async (userId: string) => {
    setLoading(true);
    const { data, error } = await supabase
      .from('proposals')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching proposals:', error);
      toast.error('Failed to load proposals');
    } else {
      setProposals(data || []);
    }
    setLoading(false);
  };

  const handleDelete = async (id: string) => {
    if (!user) return;
    setDeletingId(id);

    const { error } = await supabase
      .from('proposals')
      .delete()
      .eq('id', id)
      .eq('user_id', user.id);

    if (error) {
      toast.error('Failed to delete proposal');
    } else {
      setProposals(proposals.filter((p) => p.id !== id));
      toast.success('Proposal deleted');
    }
    setDeletingId(null);
  };

  const handleCopy = (proposal: string, id: string) => {
    navigator.clipboard.writeText(proposal);
    setCopiedId(id);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleEmailExport = (proposal: Proposal) => {
    const subject = encodeURIComponent('Application Proposal — Sovereign');
    const body = encodeURIComponent(proposal.generated_proposal);
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
    toast.success('Opening email...');
  };

  const handleDownload = (proposal: Proposal) => {
    const currentPlan = profile?.subscription_plan || 'free';
    const downloadLimit = getDownloadLimit(currentPlan);
    if (downloadLimit !== Infinity && downloadsUsed >= downloadLimit) {
      toast.error('Daily download limit reached. Upgrade for unlimited downloads.');
      return;
    }

    const content = `PROPOSAL\n${'='.repeat(50)}\n\nJob Description:\n${proposal.job_description}\n\n${'='.repeat(50)}\n\nGenerated Proposal:\n${proposal.generated_proposal}\n\n${'='.repeat(50)}\nGenerated by Sovereign AI`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `proposal-${new Date(proposal.created_at).toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setDownloadsUsed(incrementDownloadsUsed());
    toast.success('Proposal downloaded!');
  };

  const filteredProposals = proposals.filter((p) => {
    const query = searchQuery.toLowerCase();
    return (
      p.job_description.toLowerCase().includes(query) ||
      p.generated_proposal.toLowerCase().includes(query)
    );
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'sent':
        return 'bg-blue-500/10 text-blue-500 border-blue-500/20';
      case 'accepted':
        return 'bg-green-500/10 text-green-500 border-green-500/20';
      case 'rejected':
        return 'bg-red-500/10 text-red-500 border-red-500/20';
      default:
        return 'bg-muted text-muted-foreground border-border';
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <SwipeablePageWrapper>
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-xl border-b border-border">
        <div className="container mx-auto px-4 lg:px-8 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-amber-600 flex items-center justify-center shadow-gold">
                <Crown className="w-4 h-4 text-primary-foreground" />
              </div>
              <span className="text-lg font-bold text-foreground">Application History</span>
            </div>
          </div>
          <Link to="/profile">
            <Button variant="outline" size="sm" className="gap-2">
              <Settings className="w-4 h-4" />
              <span className="hidden sm:inline">Profile</span>
            </Button>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="container mx-auto px-4 lg:px-8 py-8 max-w-5xl">
        {/* Profile Summary Card */}
        <div className="rounded-xl border border-border bg-card p-6 mb-8">
          <div className="flex flex-col sm:flex-row items-center gap-6">
            {/* Avatar - supports presets */}
            {(() => {
              const presetData = getPresetAvatarData(profile?.avatar_url || null);
              return presetData ? (
                <div
                  className={`w-20 h-20 rounded-full flex items-center justify-center text-3xl border-4 border-primary/20 ${presetData.animation}`}
                  style={{ backgroundColor: presetData.bg }}
                >
                  {presetData.emoji}
                </div>
              ) : (
                <Avatar className="w-20 h-20 border-4 border-primary/20">
                  <AvatarImage
                    src={profile?.avatar_url || undefined}
                    alt={profile?.full_name || 'Profile'}
                  />
                  <AvatarFallback className="text-xl bg-primary/10 text-primary">
                    {getInitials(profile?.full_name) || <UserIcon className="w-8 h-8" />}
                  </AvatarFallback>
                </Avatar>
              );
            })()}
            
            <div className="flex-1 text-center sm:text-left">
              <h2 className="text-xl font-semibold text-foreground">
                {profile?.full_name || 'Your Profile'}
              </h2>
              {profile?.bio && (
                <p className="text-sm text-muted-foreground mt-1 line-clamp-2">{profile.bio}</p>
              )}
              {profile?.subscription_plan && profile.subscription_plan !== 'basic' && (
                <div className="mt-2 inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20">
                  <Crown className="w-3 h-3 text-primary" />
                  <span className="text-xs font-medium text-primary capitalize">
                    {profile.subscription_plan}
                  </span>
                </div>
              )}
            </div>

            {/* Stats */}
            <div className="flex gap-6 sm:gap-8">
              <div className="text-center">
                <div className="text-2xl font-bold text-foreground">{proposals.length}</div>
                <div className="text-xs text-muted-foreground">Total</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-foreground">
                  {proposals.filter(p => p.status === 'sent').length}
                </div>
                <div className="text-xs text-muted-foreground">Sent</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-green-500">
                  {proposals.filter(p => p.status === 'accepted').length}
                </div>
                <div className="text-xs text-muted-foreground">Accepted</div>
              </div>
            </div>
          </div>
        </div>

        {/* Search */}
        <div className="mb-6">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search applications..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>
        </div>

        {/* Stats Bar */}
        <div className="flex items-center gap-4 mb-6 text-sm text-muted-foreground">
          <span className="flex items-center gap-1">
            <FileText className="w-4 h-4" />
            {proposals.length} total applications
          </span>
          {searchQuery && (
            <span>• {filteredProposals.length} matching</span>
          )}
        </div>

        {/* Proposals List */}
        {filteredProposals.length === 0 ? (
          <div className="text-center py-16 rounded-xl border border-border bg-card">
            <FileText className="w-12 h-12 mx-auto mb-4 text-muted-foreground/50" />
            <h3 className="text-lg font-medium text-foreground mb-1">
              {searchQuery ? 'No applications found' : 'No applications yet'}
            </h3>
            <p className="text-sm text-muted-foreground">
              {searchQuery
                ? 'Try a different search term'
                : 'Generate your first application from the dashboard'}
            </p>
            {!searchQuery && (
              <Link to="/dashboard">
                <Button variant="gold" className="mt-4">
                  Go to Dashboard
                </Button>
              </Link>
            )}
          </div>
        ) : (
          <div className="space-y-4">
            {filteredProposals.map((proposal) => (
              <div
                key={proposal.id}
                className="rounded-xl border border-border bg-card overflow-hidden transition-all hover:border-primary/30"
              >
                {/* Header */}
                <div
                  className="p-4 cursor-pointer hover:bg-muted/30 transition-colors"
                  onClick={() =>
                    setExpandedId(expandedId === proposal.id ? null : proposal.id)
                  }
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-foreground line-clamp-2 font-medium">
                        {proposal.job_description}
                      </p>
                      <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Calendar className="w-3 h-3" />
                          {new Date(proposal.created_at).toLocaleDateString(undefined, {
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric',
                          })}
                        </span>
                        <span className="flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {new Date(proposal.created_at).toLocaleTimeString(undefined, {
                            hour: '2-digit',
                            minute: '2-digit',
                          })}
                        </span>
                        <span className={`px-2 py-0.5 rounded-full text-xs border capitalize ${getStatusColor(proposal.status)}`}>
                          {proposal.status}
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleCopy(proposal.generated_proposal, proposal.id);
                        }}
                      >
                        {copiedId === proposal.id ? (
                          <Check className="w-4 h-4 text-green-500" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDownload(proposal);
                        }}
                      >
                        <Download className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleEmailExport(proposal);
                        }}
                      >
                        <Mail className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-destructive hover:text-destructive"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDelete(proposal.id);
                        }}
                        disabled={deletingId === proposal.id}
                      >
                        {deletingId === proposal.id ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          <Trash2 className="w-4 h-4" />
                        )}
                      </Button>
                      {expandedId === proposal.id ? (
                        <ChevronUp className="w-4 h-4 text-muted-foreground" />
                      ) : (
                        <ChevronDown className="w-4 h-4 text-muted-foreground" />
                      )}
                    </div>
                  </div>
                </div>

                {/* Expanded Content */}
                {expandedId === proposal.id && (
                  <div className="border-t border-border p-4 bg-muted/20">
                    <div className="mb-4">
                      <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
                        Job Description
                      </h4>
                      <p className="text-sm text-foreground whitespace-pre-wrap">
                        {proposal.job_description}
                      </p>
                    </div>
                    <div>
                      <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
                        Generated Application
                      </h4>
                      <p className="text-sm text-foreground whitespace-pre-wrap leading-relaxed">
                        {proposal.generated_proposal}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
        
        {/* Spacer for mobile bottom nav */}
        <div className="h-20 lg:hidden" />
      </main>

      {/* Mobile Bottom Navigation */}
      <MobileBottomNav />
    </div>
    </SwipeablePageWrapper>
  );
};

export default ProposalsHistory;
