import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-4xl font-bold text-foreground mb-8">Terms of Service</h1>
          
          <div className="prose prose-lg prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-foreground text-lg">
              Last updated: January 2024
            </p>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing and using Sovereign, you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to these terms, please do not use our service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
              <p>
                Sovereign is an AI-powered productivity tool designed to assist freelancers in creating proposals and managing client communications. Our service provides AI-generated suggestions and drafts that you can review, edit, and approve before use.
              </p>
              <div className="bg-card border border-primary/30 rounded-lg p-4">
                <p className="text-foreground font-medium">
                  Important Disclaimer: Sovereign is an AI-assisted tool. AI assists users in their workflow, but all final decisions and actions belong to the user. We do not guarantee any specific outcomes, income, or success rates.
                </p>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">3. User Responsibilities</h2>
              <p>As a user of Sovereign, you agree to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Review all AI-generated content before sending or publishing</li>
                <li>Take full responsibility for any content you send to clients</li>
                <li>Provide accurate information in your profile</li>
                <li>Comply with all applicable laws and regulations</li>
                <li>Not use the service for any unlawful purposes</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">4. AI-Generated Content</h2>
              <p>
                All content generated by our AI is provided as suggestions only. You acknowledge that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI-generated content requires human review and approval</li>
                <li>You are responsible for the accuracy and appropriateness of content you use</li>
                <li>AI suggestions are not guaranteed to be error-free</li>
                <li>Final decisions about what to send to clients are yours alone</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">5. Subscription and Billing</h2>
              <p>
                Sovereign offers various subscription plans. By subscribing, you agree to pay the applicable fees. Subscriptions renew automatically unless cancelled. See our pricing page for current rates and plan details.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">6. Limitation of Liability</h2>
              <p>
                Sovereign is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">7. Modifications</h2>
              <p>
                We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">8. Contact</h2>
              <p>
                For questions about these Terms of Service, please contact us at legal@sovereign.app
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
